services:
  browser:
    container_name: gelato_browser
    # See inside via VNC with the "debug" version
    image: selenium/standalone-chrome-debug
    
    ports:
      - "5900:5900" #for VNC access
      - "4444:4444" #for webdriver access

  ruby:
    container_name: gelato_ruby
    build: .
    volumes:
      - .:/app
    depends_on: 
      - browser

networks:
  gelato:
    driver: bridge